model:
  layer_num: [2, 2, 4, 4, 4]
  num_classes: 100
  batchnorm: false

dataloader:
  batchsize: 16
  transforms:
    train:
      # - type: "RandomResizedCrop"
      #   size: 224
      - type: "RandomRotation"
        degrees: [0, 270]
      - type: "RandomHorizontalFlip"
        p: 0.5
      - type: "RandomVerticalFlip"
        p: 0.5
      - type: "Resize"
        size: [224, 224]
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.4914, 0.4822, 0.4465]
        std:  [0.247, 0.243, 0.261]
    val:
      - type: "Resize"
        size: [224, 224]
      - type: "ToTensor"
      - type: "Normalize"
        mean: [0.4914, 0.4822, 0.4465]
        std:  [0.247, 0.243, 0.261]

train:
  epochs: 100